services:

  redis:

    image: redis:latest

    container_name: redis1

    ports:

      - "6379:6379"


  mongo:

    image: mongo:latest

    container_name: mongo1

    ports:

      - "27017:27017"